Initiate bot
Rodis-Infrastructure/Azalea-Archive pull request #1
Opened 2022-12-05 18:38 UTC by Archasion

**Handlers** (with samples)

* Chat input commands
* Message context menu commands
* User context menu commands
* Buttons
* Modals
* Select menus

**Other handler features**

* Restriction utilities
* Logging utilities (with command-use-logs already implemented)

2022-12-06 13:19 UTC, TheMadKingNoah requested changes

2022-12-06 13:19 UTC, TheMadKingNoah commented on src/Bot.ts
> +                GatewayIntentBits.GuildBans,
Adding intents will add cache unless a limit has been set. What are we planning to use this intent for?

2022-12-06 13:19 UTC, TheMadKingNoah commented on src/utils/RestrictionUtils.ts
> +    Public = 0,
I find this confusing with our public sector. Discord usually defines them under @everyone.

2022-12-06 13:19 UTC, TheMadKingNoah commented on src/utils/Properties.ts
> +    public static noLogsChannels = [
"preventLogEventsChannels" or something in those lines.

2022-12-06 13:19 UTC, TheMadKingNoah commented on src/utils/Properties.ts
> +    public static noLogsChannels = [
The category "internal logs" should also be ignored.

2022-12-06 14:02 UTC, TheMadKingNoah commented
I like the response type. Would like to see a function that checks if the channel is in one of our internal channels. If true, the command reply can be visible. If false (it's in a public channel) it should reply ephemeral. You could make a separate function for it.

2022-12-06 14:05 UTC, TheMadKingNoah submitted a review, later dismissed

2022-12-06 14:05 UTC, TheMadKingNoah commented on src/utils/Properties.ts
> +    public static channels = {
Could you include "moderators and trial moderators"

2022-12-07 04:15 UTC, AmaranthineCodices requested changes
In general, I'm not fond of the following patterns in this PR.

## Performing setup actions, including network requests and websocket connections, in class constructors

This is not a great thing to do in general, but it's especially wonky when we perform asynchronous operations. We should seriously consider moving these into a dedicated `connect` or `register` method. Doing setup logic in constructors can cause all manner of issues, especially if we ever choose to unit test these classes.

## Classes as containers of methods

There is no reason to create and export a class whose sole purpose is to contain static methods. They are not retaining state. Just export the methods as free functions and drop the class indirection.

## Hard-coding configuration and permissions

We should not do this. We will be hosting (N + 1), where N is the number of people working on the bot, instances of this bot _at least_ - one per person for development, and one in production. We may well choose to have more. All of these will have different configurations, different tokens, different servers they care about, and presumably different permission needs. We _need_ this to be configurable in a configuration file that is not checked into source control.

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/Bot.ts
> +            await this.login(process.env.BOT_TOKEN);
We should absolutely not do this in the constructor. This should be a separate `connect` method.

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/handlers/interactions/buttons/Button.ts
> +            this.client.buttons.register(this);
This should not be done in the constructor.

2022-12-07 04:15 UTC, AmaranthineCodices commented on package.json
> +        "build": "tsc",
We should have tsc installed as a dev-dependency so we can pin the version.

2022-12-07 04:15 UTC, AmaranthineCodices commented on package.json
> +    "license": "ISC",
If ISC is accurate we should include the license in this repository.

2022-12-07 04:15 UTC, AmaranthineCodices commented on package.json
> +        "fs": "^0.0.1-security",
This shouldn't be here. [The package is empty.](https://www.npmjs.com/package/fs)

2022-12-07 04:15 UTC, AmaranthineCodices commented on package.json
> +        "path": "^0.12.7"
This is a [copy of a NodeJS built-in](https://www.npmjs.com/package/path) that we do not need.

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/handlers/interactions/buttons/Manager.ts
> +        const files = readdirSync(join(__dirname, "../../../interactions/buttons"))
If `load` is async, this call should be async as well.

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/handlers/interactions/commands/Manager.ts
> +        const directories = readdirSync(join(__dirname, "../../../interactions/commands"));
This call should be async.

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/handlers/interactions/commands/Manager.ts
> +            const files = readdirSync(join(__dirname, `../../../interactions/commands/${directory}`));
This call should be async.

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/handlers/interactions/modals/Manager.ts
> +        const files = readdirSync(join(__dirname, "../../../interactions/modals"))
This call should be async.

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/utils/Properties.ts
> +    Default = 2
This seems like...not the right place for this.

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/utils/Properties.ts
> +export default class Properties {
_All_ of these should be loaded out of a configuration file at runtime, not hard-coded into the bot. Doing it this way will make it really obnoxious to spin up a test instance of the bot in another guild, with different roles and channels.

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/utils/LoggingUtils.ts
> +export default class LoggingUtils {
There's no reason to put this in a class. We can just export a free function. There's no state being kept.

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/utils/LoggingUtils.ts
> +        icon?: string,
This is a type-safety hole: not all strings are valid icons. We should reflect this with a string union.

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/listeners/Ready.ts
> +module.exports = class ReadyEventListener extends EventListener {
This syntax doesn't match the rest of the codebase.

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/listeners/InteractionCreate.ts
> +module.exports = class InteractionCreateEventListener extends EventListener {
This syntax doesn't match the rest of the codebase.

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/handlers/listeners/Loader.ts
> +        const files = readdirSync(join(__dirname, "../../listeners")).filter(file => file.endsWith(".js"));
This should be async.

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/utils/RestrictionUtils.ts
> +        return member.roles.cache.has(Properties.roles.manager);
Is there a case where roles will not be in the cache, but we'll still want to know this information? Do we need to e.g. kick off a HTTP request?

2022-12-07 04:15 UTC, AmaranthineCodices commented on src/Bot.ts
> +export default class Bot extends Client {
Why do we extend `Client` instead of containing a `Client`? I vastly prefer [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance) unless there's a very compelling use case - this doesn't seem to be one.

2022-12-07 16:47 UTC, Lymia requested changes

2022-12-07 16:47 UTC, Lymia commented on src/utils/RestrictionUtils.ts
> +        return member.roles.cache.has(Properties.roles.manager);
The Discord API is very lazy with big servers like the Roblox Discord. There was a point where I had to add code in both Sylph Verifier and Rowboat to handle the case where (for whatever reason?) Discord just doesn't send off role information in the cache and I had to manually grab it using an HTTP request.

That being said, the Discord API does send role/member information with every message or command a user sends. I'm not sure if Discord.js does this, but, it's very much possible that it puts that information in the cache - in which case, there should be no case where this falls through.

2022-12-07 16:47 UTC, Lymia commented on src/utils/RestrictionUtils.ts
> +export default class RestrictionUtils {
We should probably figure this API out early, since we may want to change our moderator structure in the future. We probably shouldn't be hardcoding the fact that we have two trial stages, for example.

In general: It might be better for us to use a *permissions* system (e.g. "User X has permission Y because they're in group Z") rather than a hardcoded checks system (e.g. "The ban command checks that the user is a senior moderator") because that is way easier to reconfigure if we need to in the future.

2022-12-15 05:37 UTC, AmaranthineCodices requested changes

2022-12-15 05:37 UTC, AmaranthineCodices commented on config/guilds/150074202727251969.yaml
> +colors:
As mentioned beforehand, we **should not** check this file into source control. If you would like to write an example configuration file that lives in a dedicated folder, that's fine, but we shouldn't be checking anything resembling a production configuration into this repository.

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/handlers/interactions/buttons/Manager.ts
> +            const button = require(join(__dirname, "../../../interactions/buttons", file)).default;
FWIW I think this is deeply unfortunate; we lose all ability for `tsc` to understand the import here. This may be something to refactor in the future.

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/handlers/interactions/buttons/Manager.ts
> +            await command.execute(interaction, this.client);
...the `ts-ignore` comment here seems suspect. Why are we doing this? What alternatives exist besides turning off `tsc` for this line?

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/handlers/interactions/buttons/Manager.ts
> +        if (memberRoles && !Array.isArray(memberRoles)) memberRoles = memberRoles?.cache.map(role => role.id);
Please consider running a formatter over the codebase.

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/handlers/interactions/commands/ChatInputCommand.ts
> +    options?: ApplicationCommandOptionData[];
`options` is never actually unset, so we don't need it to be optional.

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/handlers/interactions/commands/ChatInputCommand.ts
> +    skipInternalUsageCheck?: boolean;
Same thing here - we always set this.

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/handlers/interactions/commands/ContextMenuCommand.ts
> +    skipInternalUsageCheck?: boolean;
This is never unset.

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/handlers/interactions/commands/Manager.ts
> +                const command = require(join(__dirname, `../../../interactions/commands/${directory}`, file)).default;
This require is unfortunate.

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/handlers/interactions/commands/Manager.ts
> +            await command.execute(interaction, this.client);
Why do we need `ts-ignore` here?

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/handlers/interactions/modals/Modal.ts
> +    skipInternalUsageCheck?: boolean;
This is never unset.

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/handlers/interactions/select_menus/SelectMenu.ts
> +        this.skipInternalUsageCheck = data.skipInternalUsageCheck ?? false;
This is never unset.

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/handlers/listeners/EventListener.ts
> +    once?: boolean;
This is never unset.

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/Client.ts
> +export const modalManager = new ModalHandler(client);
We should not use global state here, as a general rule. Make a separate class that owns all of this, as well as the client, that we can pass around as needed.

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/interactions/commands/chat_input/Config.ts
> +        const config: GuildConfig | undefined = globalGuildConfigs.get(guildId) ?? parse(await readFile(`config/guilds/${guildId}.yaml`, "utf-8"));
We should not have this fallback. We should have event listeners handling us being added to/removed from guilds that populate the guild configuration map. If we don't do this, we'll have to duplicate the configuration loading fallback here over and over again, or run into inconsistencies across the codebase.

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/interactions/commands/chat_input/Config.ts
> +            .setDescription(`\`\`\`json\n${JSON.stringify(config, null, 4)}\`\`\``)
It's deeply unfortunate that we're going to use YAML as the primary format, and then spit it out in JSON. Can we not use the YAML package to serialize the config back to a YAML string?

2022-12-15 05:37 UTC, AmaranthineCodices commented on src/listeners/Ready.ts
> +        }
Another way to approach this is to treat the list of configuration files as the set of allowed guilds, rather than loading configs for each guild the bot is in.

2023-01-17 00:46 UTC, AmaranthineCodices approved these changes

2023-01-17 01:27 UTC, Lymia approved these changes
While there's things I think could be improved (such as how logging and configuration loading is handled), I don't think any of it is worth blocking this PR over anymore. This is at the point where gradual patches and small refactors can sort out the remaining kinks.

Everything looks decent enough to start working on it using other PRs and stuff. Good work.

2023-01-17 01:28 UTC, merged